name: blood_gas_app
description: Offline-first Blood Gas Tracking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  drift: ^2.24.2
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.0
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2
  image: ^4.3.0
  intl: ^0.20.1
  uuid: ^4.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  image_cropper: ^10.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  drift_dev: ^2.24.2
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "logo.png"
  adaptive_icon_background: "#121218"
  adaptive_icon_foreground: "logo.png"

flutter:
  uses-material-design: true
  assets:
    - logo.png
